# Generated by Django 3.2 on 2021-04-22 04:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Titulo')),
                ('description', models.TextField(max_length=5000, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=webapp.models.Blog.image_directory_path, verbose_name='Imagen del blog')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='Ultima Modificacion')),
                ('status', models.CharField(choices=[('draft', 'Nuevo'), ('available', 'Disponible'), ('cancel', 'Deshabilitado')], default='draft', max_length=10, verbose_name='Estado')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Titulo')),
                ('text_content', models.TextField(max_length=20000, verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to=webapp.models.Article.image_directory_path, verbose_name='Imagen de articulo')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='Ultima Modificacion')),
                ('status', models.CharField(choices=[('draft', 'Nuevo'), ('available', 'Disponible'), ('cancel', 'Deshabilitado')], default='draft', max_length=10, verbose_name='Estado')),
                ('blog_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='webapp.blog', verbose_name='Blog')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
