# Generated by Django 3.2 on 2021-06-04 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_auto_20210423_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Titulo')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('image', models.ImageField(blank=True, null=True, upload_to=webapp.models.Book.image_directory_path, verbose_name='Imagen')),
                ('file', models.FileField(blank=True, null=True, upload_to=webapp.models.Book.file_directory_path, verbose_name='Archivo')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
